[package]
name = "synnapse-api"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["api", "db"]

[dependencies]
api = { path = "./api" }
clap = { version = "4.5.37", features = ["derive"] }
db = { path = "./db" }
tokio = "1.45.0"
