services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: synuser
      POSTGRES_PASSWORD: synpass
      POSTGRES_DB: synnapse
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synuser -d synnapse"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
