[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { path = "../db" }
diesel = { version = "2.2.0", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
] }
rocket = "0.5.1"
serde_json = "1.0.140"
